version: '3.9'

services:
  ai-bug-reporter-backend:
    container_name: ai-bug-reporter-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"  # Host port 8001'e güncellendi
    volumes:
      - .:/app
      - /app/venv
      - /app/__pycache__
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]  # Port tutarlı
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    networks:
      - ai-bug-reporter-network

  ai-bug-reporter-frontend:
    container_name: ai-bug-reporter-frontend
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    depends_on:
      - ai-bug-reporter-backend
    environment:
      # Frontend'in backend'e erişimi için
      - BACKEND_URL=http://ai-bug-reporter-backend:8001
    networks:
      - ai-bug-reporter-network

networks:
  ai-bug-reporter-network:
    driver: bridge